### 난수 발생 및 카운팅 , 통계 계산 함수 소개

- count(데이터의 개수)
- mean, average(평균)
- variance(분산)
- standard deviation(표준편차)
- max, min, median, quartile

- np.random.rand : 0 부터 1 사이의 균일한 값을 리턴하는 분포
- np.random.randn : 정규분포
- np.random.randint : 정수의 난수를 리턴한다 

In [4]:
import numpy as np

In [5]:
x = np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8, 2, 5, 4, -1, 4, -7, -24, 7, 9, -6, 23, 13])
print(x)

[ 18   5  10  23  19  -8  10   0   0   5   2  15   8   2   5   4  -1   4
  -7 -24   7   9  -6  23  13]


In [6]:
len(x)

25

In [7]:
#표본 평균
np.mean(x) 

5.44

In [10]:
#표본 분산
np.var(x)

105.28640000000001

In [11]:
#표본 표준편차 : 분산의 양의 제곱근
np.std(x)

10.260916138435205

In [12]:
np.max(x)

23

In [13]:
np.min(x)

-24

In [14]:
np.median(x)

5.0

In [15]:
#사분위수 : 1사분위수는 25% 백분위수와 같다.

np.percentile(x,0)
np.percentile(x,25)
np.percentile(x,50)
np.percentile(x,75)
np.percentile(x,100)

23.0

- random 서브패키지에 난수를 발생시키는 함수 제공
- np.random.seed(0)

In [24]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

- 데이터 샘플링 / train, test set 나눌 때 
- choice(배열, size = 샘플링 숫자, replace=T, p=각 데이터가 선택될 확률)

In [29]:
np.random.choice(5 , 5, replace=False) #True는 복원 추출, False는 비복원 추출

array([2, 4, 1, 3, 0])

In [37]:
np.random.choice(5 , 10, p=[0.1, 0.2, 0.3, 0.4, 0]) #p는 가중치를 줘서 선택될 수 있는 확률을 높일 수 있다.

array([1, 2, 2, 2, 2, 3, 1, 1, 1, 3], dtype=int64)